---
title: "Annual Mobility Report 2024"
format: 
  html:
      toc: true
      toc_float: true
      toc-title: Contents
      toc_location: left
editor: visual
number-sections: true
execute: 
  echo: false
  warning: false
  message: false
  fig.with: 9
---

```{r package}

library(tidyverse)
library(ggplot2)
library(plotly)
library(dplyr)
```

# Data Preparation

-   In order to analyze trends of sale between several fiscal years, historical daily PL needs to be combined.

-   The combined data consists of P&L data from X Department between FY2021 and FY2024.

```{r}
df <- read.csv("~/GitHub/amr_2024/data/NF_Bike_Ped_fatalcrashes_19_23.csv")
```

# Plot with data

This plot shows fatality data

```{r}
p <- ggplot(df, aes(x = Year, y = PedFatal, fill = County)) +
  geom_col() +
  theme_minimal()+
  geom_text(aes(label = PedFatal),  # Add text labels
            size = 5,# Adjust vertical position (above bars)
            hjust = .5,                # Adjust horizontal position (center)
            position=position_stack(vjust=.5),
            check_overlap=TRUE) 

# Convert to an interactive plotly object
p_interactive <- ggplotly(p, tooltip = c("PedFatal","County")) %>%
  layout(yaxis = list(title = "Pedestrian Fatalities", zeroline = FALSE, 
                      showline = FALSE), barmode = 'stack',
         hoverlabel = list(bgcolor= 'white')) 

p_interactive
```
```{r}
p <- ggplot(df, aes(x = Year, y = BikeFatal, fill = County)) +
  geom_col() +
  theme_minimal()+
  geom_text(aes(label = BikeFatal),  # Add text labels
            size = 5,# Adjust vertical position (above bars)
            hjust = .5,                # Adjust horizontal position (center)
            position=position_stack(vjust=.5),
            check_overlap=TRUE) 

# Convert to an interactive plotly object
p_interactive <- ggplotly(p, tooltip = c("BikeFatal","County")) %>%
  layout(yaxis = list(title = "Bicyclist Fatalities", zeroline = FALSE, 
                      showline = FALSE), barmode = 'stack',
         hoverlabel = list(bgcolor= 'white')) 

p_interactive
```


```{r}
library(plotly)
df <- read.csv("https://raw.githubusercontent.com/plotly/datasets/master/2011_us_ag_exports.csv")
df$hover <- with(df, paste(state, '<br>', "Beef", beef, "Dairy", dairy, "<br>",
                           "Fruits", total.fruits, "Veggies", total.veggies,
                           "<br>", "Wheat", wheat, "Corn", corn))
# give state boundaries a white border
l <- list(color = toRGB("white"), width = 2)
# specify some map projection/options
g <- list(
  scope = 'usa',
  projection = list(type = 'albers usa'),
  showlakes = TRUE,
  lakecolor = toRGB('white')
)

fig <- plot_geo(df, locationmode = 'USA-states')
fig <- fig %>% add_trace(
    z = ~total.exports, text = ~hover, locations = ~code,
    color = ~total.exports, colors = 'Purples'
  )
fig <- fig %>% colorbar(title = "Millions USD")
fig <- fig %>% layout(
    title = '2011 US Agriculture Exports by State<br>(Hover for breakdown)',
    geo = g
  )

fig

```
